const affirmations = {
  Morning: [" I am feeling healthy and strong today.",
    "I am open and receptive to healing energy.",
    "My body is worthy of love and healthy choices.",
    "I thank my body through exercise and healthy choices.",
    "I am a healthy and happy person.",
    "My body is a vessel of wellness.",
    "I lovingly do everything I can to assist my body in maintaining health.",
    "Today I focus on what makes me feel good.",
    "Today is going to be a really, really good day.",
    "I am excited to wake up each morning and experience this beautiful life, that I am creating with my thoughts and visions.",
    "Every day is a new beginning. Take a deep breath, smile, and start again.",
    "My life is a gift. I will use this gift with confidence, joy, and exuberance.",
    "Today I align myself with freedom, growth, and joy.",
    "I release all resistance of the past and move into the present moment.",
    "No negative thought will take root in my mind.",
    "I am joyful every day and create joy for others.",
    "My life is a blast of growing opportunity because I never stop creating.", //17
    "I am fulfilling my purpose in this world.",
    "I give myself permission to go after what I want.",
    "I have the power to create all the success and prosperity I desire.",
    "I am grateful that my life is so happy and successful.",
    "I wake up every morning ready for a new day of exciting possibilities.",
    "To be positive is to be productive.",
    "Today I abandon my old habits and take up new, more positive ones.",
    "I am determined and will never give up.", //25
    "I believe in my ultimate potential.", //26
    "My thoughts do not control me, I control my thoughts.",
    "I am thankful for what I have, even if it is not perfect.",
    "I work well under pressure and always feel motivated.", //29
    "I have everything I need to face any obstacles that come.",
    "I am learning to trust the journey.",
    "I greet this day with confidence and ease.",
    "I can easily focus on finishing my tasks.",
    "My mind is clear and focused.", //34,
    "I love accomplishing things.",
    "I am motivated to work hard today.",//36
    "Today is a beautiful day.",
    "I am dedicated to becoming a better person.",
    "Everything is working well for me.",
    "I accept every situation as it is.",
    "I am strong, energized and full of vitality.",
    "I am ready to have an amazing day.",
    "I am motivated to have a productive day.", //43
    "I am motivated do exercise daily.",
    "I am committed to finishing my exercises.",
    "I am getting the body I always wanted.",
    "Motivation for exercise comes easily to me.",
    "I love exercising and working out.",
    "I am going to have a great workout."
  ],
  Afternoon: ["I am successful.",
    "I am confident.",
    "I am powerful.",
    "I am strong.",
    "I am getting better and better every day.",
    "All I need is within me right now.",
    "I am an unstoppable force of nature.",
    "I am a living, breathing example of motivation.",
    "I am living with abundance.",
    "I am having a positive and inspiring impact on the people I come into contact with.",
    "I am inspiring people through my work.",
    "I’m rising above the thoughts that are trying to make me angry or afraid.",
    "I am turning DOWN the volume of negativity in my life, while simultaneously turning UP the volume of positivity.",
    "I am filled with focus.",
    "I am not pushed by my problems; I am led by my dreams.",
    "I am grateful for everything I have in my life.",
    "I am independent and self-sufficient.",
    "I can be whatever I want to be.",
    "I am not defined my by past; I am driven by my future.",
    "I use obstacles to motivate me to learn and grow.",
    "I am intelligent and focused.",
    "I feel more grateful each day.",
    "I am getting healthier every day.",
    "Each and every day, I am getting closer to achieving my goals.",
    "Through the power of my thoughts and words, incredible transformations are happening in me and within my life right now.",
    "I am constantly growing and evolving into a better person.",
    "I’m freeing myself from all destructive doubt and fear.",
    "I accept myself for who I am and create peace, power and confidence of mind and of heart.",
    "I am going to forgive myself and free myself. I deserve to forgive and be forgiven.",
    "I am healing and strengthening every day.",
    "I’ve made it through hard times before, and I’ve come out stronger and better because of them. I’m going to make it through this.",
    "I do not waste away a single day of my life. I squeeze every ounce of value out of each of my days on this planet—today, tomorrow, and everyday.",
    "I must remember the incredible power I possess within me to achieve anything I desire.",
    "I do not engage with people who try to penetrate my mind with unhelpful thoughts and ideas—I walk away when a person or a situation isn’t healthy for me.",
    "I belong in this world; there are people that care about me and my worth.",
    "My past might be ugly, but I am still beautiful.",
    "I have made mistakes, but I will not let them define me.",
    "My soul radiates from the inside and warms the souls of others.",
    "I don’t compare myself to others. The only person I compare myself to is the person I was yesterday. And as long as the person I am today is even the tiniest bit better than the person I was yesterday—I’m meeting my own definition of success.",
    "Note to self: I am going to make you so proud.",
    "I finish what matters and let go of what does not.",
    "I feed my spirit. I train my body. I focus my mind. This is my time.",
    "My life has meaning. What I do has meaning. My actions are meaningful and inspiring.",
    "What I have done today was the best I was able to do today. And for that, I am thankful.",
    "One small positive thought in the morning can change my whole day. So, today I rise with a powerful thought to set the tone and allow success to reverberate through every moment of my day.",
    "I set goals and go after them with all the determination I can muster. When I do this, my own skills and talents will take me to places that amaze me.",
    "Happiness is a choice, and today I choose to be happy."
  ],
  Evening: ["I’m not where I want to be but I’m willing to do the work needed to get better.",
    "Even though I feel exhausted right now, I have to keep working, I’m almost at the finish line. I know I have what it takes to accomplish my goals.",
    "All my work is a self-transformative process, bringing inner peace, excellent health and prosperity to me and others.",
    "I am successful. Recent setbacks do not negate my previous successes.",
    "All of these late nights and early mornings are going to pay off one day. I’m going to keep working until I am where I know I belong.",
    "I know that all of this is going to pay off. I just have to stay consistent. It’s not always easy but this is all going to work out in the end.",
    "I will invest in myself because I am worth it.",
    "I fully accept myself and know that I am worthy of great things in life. I find deep inner peace within myself as I am.",
    "Things are going to work out for me. I just have to keep putting in the work to make that happen.",
    "I have to work even when I don’t feel inspired.",
    "I don’t need to be embarrassed that I’m not where I want to be because I will reach there eventually.",
    "I deserve the best and I accept the best now.",
    "I’m going to keep the promises I made to myself and accomplish every goal I’ve written down.",
    "I have to keep talking to myself more positively. I’m going to practice until it becomes a habit and I’m going to work on the habit every day until it feels natural.",
    "A goal I’m setting for myself is to exercise and eat well every day.",
    "No more giving up when I feel tired. I’m going to give my best until my goals are complete.",
    "My doubts will not kill my dreams. I’m going to work until I’m where I want to be.",
    "No more letting bad days distract me from my goals.",
    "I want to maintain is consistency. Every day do one productive thing to get closer to my goals.",
    "Now isn’t the time to wish I had done more before, It’s time for me to double up and do more now.",
    "My wins are coming soon. I just have to remain patient and keep working.",
    "No more wasting my time and energy on comparing, complaining and competing. From now on it’s full focus on creating.",
    "My work fulfills, inspires and enriches me.",
    "Today and every day, I bring light into the workplace with me! I refuse to allow anyone to extinguish my light!",
    "I’m going to stay focused on my goals. Let them gossip about whatever they want too.",
    "In order to build discipline I have to work on myself even when I don’t feel like it.",
    "I learn from my mistakes and give myself grace and love.",
    "All of these late nights and early mornings are going to pay off one day. I’m going to keep working until I am where I know I belong.",
    "No more letting bad days distract me from my goals.",
    "Every difficult experience is a learning experience.",
    "I’m going to create my own opportunities I’m not going to sit around and wait for somebody to come to help me out",
    "I enjoy making money and strive to have fun in every aspect of my work.",
    "I am positive and optimistic. I believe things will always work out for the best.",
    "These workouts are investments into a better me. Who I’m becoming will thank me later for the work I’m putting in now.",
    "Tonight I’m deciding that my goals are more important than going out and chilling. I’ll have other times to relax, but tonight I got to get focused and work.",
    "I’m building my skillset so I can rely on my talents to make a living.",
    "No one has the power to stop my dreams from coming true.",
    "My talent is going to create a better future for me. I have to keep practicing and investing in my abilities.",
    "I’m working hard to make all of the people who have made sacrifices for me proud.",
    "Only thing I can do now is to keep doing what I’m supposed to be doing and the win is going to come.",
    "At work, my mind is focused and I have clarity and energy in all that I do.",
    "I will work honestly. I will put my heart and soul into my work.",
    "I am happy that the work I do benefits me as well as the society I live in.",
    "The people I love deserve better than how we are living. I’m working to give them more.",
    "My work is always recognized for excellence.",
    "I work very hard, and I always do my best. I believe in myself. I can do everything!",
    "I envision myself wealthy in every area of my life and work towards that reality.",
    "Amazing opportunities exist for me in every aspect of my life.",
    "Things are going to work out for me. I just have to keep putting in the work to make that happen.",
    "I know can do better. So instead of settling, I’m going to do better.",
    "I’m not going to give in to my doubts. I know I’m not where I want to be right now but I will get there eventually if I keep working.",
    "I’m making plans for who I know I’m going to become. All of this work isn’t for nothing."
  ],
  Night: ["I am thankful for today.",
    "I feel calm and at peace.",
    "I am in control of my thoughts and I choose positive ones.",
    "I choose calm. I choose peace.",
    "I let go of my responsibilities of the day.",
    "I let go of worry.",
    "I let go of what I can’t control.",
    "I release anything that didn’t go well today.",
    "My to-do list will wait for tomorrow.",
    "Nothing will disturb my peace unless I let it.",
    "I let go of the past and the future. I focus on the present moment.",
    "I let go of tense thoughts.",
    "I am still and calm.",
    "I breathe deeply and slowly.",
    "I am grateful for the simple and profound joys of the day.",
    "I am grateful for my bed, my room, and my quieting body.",
    "I give myself permission to do nothing.",
    "I am enough. I did enough. I can let go.",
    "I forgive myself for any mistakes made today.",
    "I forgive others that made mistakes today. We are all human.",
    "I am allowed to feel good at the end of the day.",
    "I release the anxieties and stress of the day.",
    "I am grateful for the lessons that today brought.",
    "Peace and happiness are my priority as I finish my day.",
    "I worked hard today, and deserve to rest. There is nothing more I can do tonight.",
    "I give myself permission to sleep deeply.",
    "My body feels heavy and relaxed.",
    "My body and mind need rest and rejuvenation to function well.",
    "Sleep and rest are essential to my success.",
    "I did my best today and now I rest.",
    "My eyes and head feel heavy.",
    "I embrace rest. I welcome sleep.",
    "I am safe in my room. I can relax completely.",
    "May my sleep be calm and peaceful.",
    "My mind and spirit are still and tranquil.",
    "There is nothing I need to do to fall asleep. I can simply let it happen.",
    "I relax my head, face, neck, arms, stomach, legs, and feet. I let them sink deeply into the bed.",
    "I empty my head of racing thoughts. I let them float along, or I tuck them away for another time.",
    "I will wake refreshed and happy after a good night’s sleep.",
    "Tomorrow will be a fantastic day.",
    "I unplug tonight in order to conquer the day tomorrow.",
    "Tomorrow I will wake up with a positive attitude.",
    "I worked today for a better tomorrow.",
    "Tomorrow is full of fresh possibilities.",
    "I will wake strong, inspired, and energized tomorrow.",
    "I have prepared myself for a beautiful morning.",
    "I am grateful for the opportunity to care for my family.",
    "I did my best today with my children, and that is enough.",
    "No one needs me now. It’s time to be kind to myself and let go."
  ]
};
module.exports = affirmations;
